/**
 * NeuroViz - Export Utilities
 * Handles exporting visualizations in various formats
 */

const NeuroVizExport = (() => {
    'use strict';

    /**
     * Export the current view as PNG
     */
    function exportPNG(elementId, filename = 'neuroviz-export.png') {
        const element = document.getElementById(elementId);
        if (!element) return;

        // Use html2canvas-like approach with canvas
        const canvas = document.createElement('canvas');
        const rect = element.getBoundingClientRect();
        const scale = 2;

        canvas.width = rect.width * scale;
        canvas.height = rect.height * scale;
        const ctx = canvas.getContext('2d');
        ctx.scale(scale, scale);

        // Background
        const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
        ctx.fillStyle = isDark ? '#0f1117' : '#f8f9fc';
        ctx.fillRect(0, 0, rect.width, rect.height);

        // Watermark
        ctx.fillStyle = isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)';
        ctx.font = '12px Inter, sans-serif';
        ctx.textAlign = 'right';
        ctx.fillText('Generated by NeuroViz', rect.width - 10, rect.height - 10);

        const link = document.createElement('a');
        link.download = filename;
        link.href = canvas.toDataURL('image/png');
        link.click();
    }

    /**
     * Export attention data as JSON
     */
    function exportAttentionJSON(attentionData, tokens, filename = 'attention-data.json') {
        const data = {
            tokens: tokens.map((t) => t.text),
            attention: attentionData.map((layerHeads, l) =>
                layerHeads.map((matrix, h) =>
                    Array.from({ length: matrix.length }, (_, i) =>
                        Array.from(matrix[i])
                    )
                )
            ),
            exportedAt: new Date().toISOString(),
            generator: 'NeuroViz v1.0.0',
        };

        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const link = document.createElement('a');
        link.download = filename;
        link.href = URL.createObjectURL(blob);
        link.click();
    }

    /**
     * Export embedding data as CSV
     */
    function exportEmbeddingCSV(embeddings, tokens, filename = 'embeddings.csv') {
        let csv = 'token,id,' + Array.from({ length: embeddings[0].length }, (_, i) => `dim_${i}`).join(',') + '\n';
        tokens.forEach((token, i) => {
            csv += `"${token.text}",${token.id},${Array.from(embeddings[i]).join(',')}\n`;
        });

        const blob = new Blob([csv], { type: 'text/csv' });
        const link = document.createElement('a');
        link.download = filename;
        link.href = URL.createObjectURL(blob);
        link.click();
    }

    /**
     * Export the full session report as Markdown
     */
    function exportReport(tokens, modelType, filename = 'neuroviz-report.md') {
        const model = NeuroVizModels.getModel(modelType);
        let md = `# NeuroViz Analysis Report\n\n`;
        md += `**Generated**: ${new Date().toLocaleString()}\n`;
        md += `**Model**: ${model.name}\n`;
        md += `**Input**: "${tokens.map((t) => t.text).join(' ')}"\n`;
        md += `**Tokens**: ${tokens.length}\n\n`;

        md += `## Model Architecture\n\n`;
        md += `| Layer | Type | Output Shape |\n`;
        md += `|-------|------|-------------|\n`;
        model.layers.forEach((layer) => {
            md += `| ${layer.name} | ${layer.type} | \`${layer.outputShape}\` |\n`;
        });

        md += `\n## Token Details\n\n`;
        md += `| Index | Token | ID |\n`;
        md += `|-------|-------|-----|\n`;
        tokens.forEach((t, i) => {
            md += `| ${i} | ${t.text} | ${t.id} |\n`;
        });

        md += `\n---\n*Generated by [NeuroViz](https://github.com/gitstq/NeuroViz) v1.0.0*\n`;

        const blob = new Blob([md], { type: 'text/markdown' });
        const link = document.createElement('a');
        link.download = filename;
        link.href = URL.createObjectURL(blob);
        link.click();
    }

    return {
        exportPNG,
        exportAttentionJSON,
        exportEmbeddingCSV,
        exportReport,
    };
})();
